### ISSUE TITLE
Using this in archiver utility

### ISSUE THREAD

**Issue by mholt** [ulikunitz/xz#10]
Hi, this isn't an issue (so you can close this) -- I just wanted to thank you for this package. I've added .tar.xz support to [archiver](https://github.com/mholt/archiver) after [a request](https://github.com/mholt/archiver/issues/14) for it.

I know you've said in another issue that this is "pre-alpha" work, and that's fine, but just so you know it's being used now. :+1:

**Comment by ulikunitz** [comment]
Hi, thank you for the positive feedback. This is motivating to get back on working on it.
