### ISSUE TITLE
use of internal package github.com/ulikunitz/xz/internal/xlog not allowed

### ISSUE THREAD

**Issue by xaionaro** [ulikunitz/xz#24]
I'm trying to build my program that uses your library and getting this error:
```
vendor/github.com/ulikunitz/xz/reader.go:17:2: use of internal package github.com/ulikunitz/xz/internal/xlog not allowed
```

The dependency:
```
    "github.com/ulikunitz/xz"
```

I added it to `vendor/` using `govendor add`.

**Comment by ulikunitz** [comment]
Please check whether vendor/github.com/ulikunitz/xz/internal/xlog actually exists. I have seen reports that govendor isn't smart enough to handle the dependency.

**Comment by xaionaro** [comment]
Yep, you right. A missing dependency.
