### ISSUE TITLE
7z

### ISSUE THREAD

**Issue by 89z** [ulikunitz/xz#36]
Is this package able to handle 7z files?

https://en.wikipedia.org/wiki/7z

**Comment by ulikunitz** [comment]
The package doesn't handle 7z files. 7z is a containder format. The focus of this package is the xz format, which supports primarily the LZMA2 compression streams.

**Comment by a8nJ** [comment]
Yeah, I didnt seem to find a Go package for this, so I think I will try this Rust one

https://github.com/gendx/lzma-rs

**Comment by ulikunitz** [comment]
According to the description of the module, it doesn't support 7z, but plans to support it later.

**Comment by 89z** [comment]
Not sure why I didnt find it before, but this one works:

https://github.com/saracen/go7z
