### ISSUE TITLE
How to use multi CPU work for compression?

### ISSUE THREAD

**Issue by bqf9979** [ulikunitz/xz#38]
The new version of XZ utils supports multi CPU simultaneous compression, which will greatly improve the efficiency. How to implement it,thanks!

**Comment by ulikunitz** [comment]
Sorry, the library doesn't support multiple CPUs right now.

**Comment by bqf9979** [comment]
ohh



---Original---

**Comment by ulikunitz** [comment]
This is a duplicate of #18 and I close it therefore.
