### ISSUE TITLE
How to write compress & decompress data in file?

### ISSUE THREAD

**Issue by jjkim0816** [ulikunitz/xz#43]
I want to compress xz type, but I don't know how to write to file.

Could you give me answer this question?

And how to decompress from xz file?

Thank you so much~^^

**Comment by ulikunitz** [comment]
I will prove an example later. In the meanwhile look at the example in the [README](https://github.com/ulikunitz/xz/blob/master/README.md). You need to replace the buffer with a file. File handling is provided by the [os](https://pkg.go.dev/os) package.

**Comment by ulikunitz** [comment]
Hi, I have added examples for reading and writing files in https://github.com/ulikunitz/xz/blob/master/example_test.go.

I will not create a release for it, but I regard the issue as addressed.
