### ISSUE TITLE
Out of Memory bug when using a large reader

### ISSUE THREAD

**Issue by amaanq** [ulikunitz/xz#46]
This had me scratching my head today for a solution-

I am decompressing many files, however a few wouldn't work because they are large and I would get out of memory panics. I looked at my code and saw I was reading the full file into a byte slice which is expensive memory-wise. I rewrote the code to use io.Readers of sorts. Now, even with that I still get out of memory panics. Looking at the source code, the issue lies with ReaderConfig.NewReader calling newDecoderDict, which calls newBuffer which makes a byte slice of the buffer size, which is exactly what I had fixed in my own code. Now I am asking, is it possible to remedy this, and if so, could we?

Thanks,

**Comment by ulikunitz** [comment]
The reader, decompressing the data, doesn't control the dictionary size. It cannot know up-front, whether the dictionary size will be used or not. So you need to control the dictionary capacity (parameter DictCap) before compression. 

 Gzip has a fixed size for the dictionary of 32 kbyte, which is a reasonable value, but compression rate will increase slightly with larger buffers. Above 1 MB the improvements are only marginal. The default in the current version is 8 MB (called DictCap) is too large. Note that the dictionary capacity doesn't need to be larger than the file you want to compress.

Note that the new version I'm currently working on will change the parameter handling in an incompatible manner, but it will not change the fact that the dictionary size must be controlled for the compressor.

**Comment by amaanq** [comment]
I'm decompressing data using LZMA, what I do currently is just feed an io.Reader, then read from it. However, feeding it into lzma.NewReader is exactly what causes this out of memory issue. I am not too familiar with the low level specs of compression and lzma, but to remedy this is there some setting I could set before feeding it into NewReader? 

On a side note, is it possible you and I could work to implement the LZHAM algorithm (https://github.com/richgel999/lzham_codec)? It is currently written only in c++, with a python and rust port merely existing by using the C++ code anyways. 

Thank you very much for the speedy reply,
Amaan

**Comment by ulikunitz** [comment]
Which software or program generates the LZMA stream? This program controls the window size which is encoded in the LZMA header.

Unfortunately I have not enough time to work on the LZHAM algorithm. I focus currently on rewriting the LZMA codec and provide a parallel encoding option.
