### ISSUE TITLE
Cannot decompress some archives

### ISSUE THREAD

**Issue by djmdjm** [ulikunitz/xz#8]
Some xz archives fail part way during decompression. Quite a few of the Linux kernel releases fall into this category.

You can reproduce it via:

```
[djm@demiurge ~]$ wget -q https://www.kernel.org/pub/linux/kernel/v3.0/linux-3.13.tar.xz                                                                    
[djm@demiurge ~]$ xzcat linux-3.13.tar.xz | wc -c
549816320
[djm@demiurge ~]$ gxz -dc linux-3.13.tar.xz | wc -c
201330688
[djm@demiurge ~]$ echo $?
```

Note that the truncation is silent - no error is written to stderr and the exit status is 0. The problem isn't in cmd/xz - I noticed it first using the library directly.

**Comment by ulikunitz** [comment]
The Reader in the dev branch supporrs now multiple xz streams. See TestReaderMultipleStreams. Th

**Comment by djmdjm** [comment]
Thanks! Do you have any idea when this feature will make it into a release?

**Comment by ulikunitz** [comment]
My plan is to do it this week.

Damien Miller <notifications@github.com> schrieb am Mo., 4. Juli 2016 01:32:

**Comment by ulikunitz** [comment]
The release v0.5 is now out. Please note that the API has changed.
